### ISSUE TITLE
utilização de param no Rmd

### ISSUE THREAD

**Issue by jpcaveiro** [jpcaveiro/rmdmoodle#34]
https://bookdown.org/yihui/rmarkdown/parameterized-reports.html

Especificar assim:

```
---
title: My Document
output: html_document
params:
  year: 2018
  region: Europe
  printcode: TRUE
  data: file.csv
---
```

Ideia 1:

* Os `param` colocam-se como em baixo e a ideia seria usar o set.seed(params$set.seed), param$VAR, etc. 

Ideia 2:

* usar `param` para colocar os parâmetro o enredo e depois durante o Rmd usar `params$amostra` e assim acaba o `nome[[VAR]]` pois pode-se usar 
```
rmarkdown::render("EnredoComAlineas.Rmd", params = list(
  year = 2017,
  region = "Asia",
  printcode = FALSE,
  file = "file2.csv"
))
```
