### ISSUE TITLE
Evitar "wrap" feito pelo pandoc pois quebra instruções cloze em várias linhas

### ISSUE THREAD

**Issue by jpcaveiro** [jpcaveiro/rmdmoodle#64]
* rmarkdown pass parameters to pandoc
* https://gemini.google.com/app/6787995fb897fa3b

Hipótese 1

```
---
title: "My Document"
params:
  include_toc: TRUE
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (params$include_toc) {
  pandoc_args <- c("--toc")
} else {
  pandoc_args <- c() # No TOC
}

rmarkdown::render(self_contained = TRUE, pandoc_args = pandoc_args)
```

Hipótese 2

``` 
---
title: "My Document"
author: "Your Name"
date: "2023-10-27"
output:
  pdf_document:
    pandoc_args: ["--toc", "--number-sections", "--template=my_custom_template.tex"]
  html_document:
    pandoc_args: ["--css=styles.css", "--metadata=custom_field:My Value"]
---

Your R Markdown content here.
```
